name: test
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  busted:
    name: tests
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup ‘lua’
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1"

    - name: setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4

    - name: setup dependencies
      run: |
        luarocks install busted
        luarocks install luacov-coveralls

    - name: run
      run: busted -c -v
      env:
        LUA_PATH: "$PWD/?.lua;$PWD/lua/?/init.lua;$PWD/lua/?.lua;$LUA_PATH"

    - name: report
      if: success()
      continue-on-error: true
      run: luacov-coveralls -i cassowary -e .luarocks
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
