name: test
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  busted:
    name: tests
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup ‘lua’
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.1"

    - name: setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4

    - name: setup dependencies
      run: |
        luarocks install busted
        luarocks install luacov

    - name: run
      run: busted -c -v
      env:
        LUA_PATH: "/home/runner/work/tmux.nvim/tmux.nvim/?.lua;/home/runner/work/tmux.nvim/tmux.nvim/lua/?/init.lua;/home/runner/work/tmux.nvim/tmux.nvim/lua/?.lua;/home/runner/work/tmux.nvim/tmux.nvim/spec/?/init.lua;/home/runner/work/tmux.nvim/tmux.nvim/spec/?.lua;"

    - name: report to codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true
